environment: prod

apiGateway:
  corsAllowedOrigins: ""

workflowService:
  workerConsumerName: workflow-service-prod

ingress:
  enabled: true
  className: nginx
  host: ""
  tls:
    enabled: false
