"""Local SMTP notification provider and templates."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from email.message import EmailMessage
from os import environ
import smtplib
from uuid import uuid4


NOTIFICATION_PROVIDER_ENV = "NOTIFICATION_PROVIDER"
SMTP_HOST_ENV = "SMTP_HOST"
SMTP_PORT_ENV = "SMTP_PORT"
SMTP_FROM_ENV = "SMTP_FROM"

LOCAL_SMTP_PROVIDER = "local-smtp-provider"
NOTIFICATION_STATUS_SENT = "sent"
NOTIFICATION_STATUS_FAILED = "failed"
NOTIFICATION_CHANNEL_EMAIL = "email"

DEFAULT_SMTP_HOST = "mailpit"
DEFAULT_SMTP_PORT = 1025
DEFAULT_SMTP_FROM = "no-reply@retailops.local"

TEMPLATE_KEYS = (
    "order_created",
    "invoice_generated",
    "payment_completed",
    "payment_failed",
    "receipt_generated",
    "workflow_completed",
)


@dataclass(frozen=True)
class RenderedNotification:
    subject: str
    message: str


@dataclass(frozen=True)
class NotificationProviderRequest:
    notification_id: str
    order_id: str
    recipient: str
    template_key: str
    subject: str
    message: str


@dataclass(frozen=True)
class NotificationProviderResult:
    status: str
    provider: str
    provider_reference: str | None
    sent_at: datetime | None
    delivery_attempts: int
    last_error: str | None


def render_template(*, template_key: str, order_id: str) -> RenderedNotification:
    subjects = {
        "order_created": "Local workflow order created",
        "invoice_generated": "Local workflow invoice generated",
        "payment_completed": "Local workflow payment completed",
        "payment_failed": "Local workflow payment failed",
        "receipt_generated": "Local workflow receipt generated",
        "workflow_completed": "Local workflow completed",
    }
    subject = subjects[template_key]
    message = (
        f"{subject} for order {order_id}.\n\n"
        "This message was generated by RetailOps-microservices-platform "
        "local notification-service."
    )
    return RenderedNotification(subject=subject, message=message)


def notification_provider_name() -> str:
    return environ.get(NOTIFICATION_PROVIDER_ENV, "local_smtp")


class LocalSmtpNotificationProvider:
    def __init__(
        self,
        *,
        smtp_host: str | None = None,
        smtp_port: int | None = None,
        smtp_from: str | None = None,
    ) -> None:
        self._smtp_host = smtp_host or environ.get(SMTP_HOST_ENV, DEFAULT_SMTP_HOST)
        self._smtp_port = smtp_port or int(
            environ.get(SMTP_PORT_ENV, str(DEFAULT_SMTP_PORT))
        )
        self._smtp_from = smtp_from or environ.get(SMTP_FROM_ENV, DEFAULT_SMTP_FROM)

    def send(self, request: NotificationProviderRequest) -> NotificationProviderResult:
        provider_reference = f"local-mail-{uuid4().hex}"
        message = EmailMessage()
        message["From"] = self._smtp_from
        message["To"] = request.recipient
        message["Subject"] = request.subject
        message["Message-ID"] = f"<{provider_reference}@retailops.local>"
        message.set_content(request.message)

        try:
            with smtplib.SMTP(self._smtp_host, self._smtp_port, timeout=5) as smtp:
                smtp.send_message(message)
        except Exception as exc:
            return NotificationProviderResult(
                status=NOTIFICATION_STATUS_FAILED,
                provider=LOCAL_SMTP_PROVIDER,
                provider_reference=None,
                sent_at=None,
                delivery_attempts=1,
                last_error=str(exc),
            )

        return NotificationProviderResult(
            status=NOTIFICATION_STATUS_SENT,
            provider=LOCAL_SMTP_PROVIDER,
            provider_reference=provider_reference,
            sent_at=datetime.now(UTC),
            delivery_attempts=1,
            last_error=None,
        )
