apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    {{- include "mwp.labels" . | nindent 4 }}
    app.kubernetes.io/component: common-config
data:
  ENVIRONMENT: {{ .Values.environment | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  WORKFLOW_COMMANDS_STREAM: {{ .Values.common.workflowCommandsStream | quote }}
  WORKFLOW_EVENTS_STREAM: {{ .Values.common.workflowEventsStream | quote }}
  WORKFLOW_DEAD_LETTER_STREAM: {{ .Values.common.workflowDeadLetterStream | quote }}
  DOCUMENT_STORAGE_DIR: {{ .Values.documentStorage.mountPath | quote }}
  PAYMENT_PROVIDER: {{ .Values.common.paymentProvider | quote }}
  NOTIFICATION_PROVIDER: {{ .Values.common.notificationProvider | quote }}
  JWT_ALGORITHM: {{ .Values.common.jwtAlgorithm | quote }}
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.common.jwtAccessTokenExpireMinutes | quote }}
