apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  labels:
    {{- include "mwp.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification-service
data:
  SMTP_HOST: "mailpit"
  SMTP_PORT: {{ .Values.mailpit.smtpPort | quote }}
  SMTP_FROM: {{ .Values.mailpit.smtpFrom | quote }}
