apiVersion: v1
kind: Service
metadata:
  name: frontend-dashboard
  labels:
    {{- include "mwp.componentLabels" (dict "root" . "component" "frontend-dashboard") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mwp.componentSelectorLabels" (dict "root" . "component" "frontend-dashboard") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.servicePort }}
      targetPort: http
