apiVersion: v1
kind: Service
metadata:
  name: mailpit
  labels:
    {{- include "mwp.componentLabels" (dict "root" . "component" "mailpit") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mwp.componentSelectorLabels" (dict "root" . "component" "mailpit") | nindent 4 }}
  ports:
    - name: smtp
      port: {{ .Values.mailpit.smtpPort }}
      targetPort: smtp
    - name: http
      port: {{ .Values.mailpit.uiPort }}
      targetPort: http
