apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "mwp.componentLabels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mwp.componentSelectorLabels" (dict "root" . "component" "postgres") | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.servicePort }}
      targetPort: postgres
