apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    {{- include "mwp.labels" . | nindent 4 }}
    app.kubernetes.io/component: app-secrets
type: Opaque
stringData:
  DATABASE_URL: {{ include "mwp.databaseUrl" . | quote }}
  REDIS_URL: {{ .Values.appSecrets.redisUrl | quote }}
  JWT_SECRET_KEY: {{ .Values.appSecrets.jwtSecretKey | quote }}
